language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
notifications:
  webhooks:
    urls:
      - http://webhooks.nodejitsu.com/1/deploy
    on_success: always
    on_failure: never
before_script:
  - npm install -g grunt-cli
